# Generated by Django 5.0.1 on 2024-02-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0002_alter_product_options_alter_subtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_pr',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_pr',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
