# Generated by Django 5.0.1 on 2024-02-26 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0004_alter_product_title_pr_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_at',
        ),
        migrations.AddField(
            model_name='product',
            name='date_finish',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала тура'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала тура'),
        ),
        migrations.AddField(
            model_name='product',
            name='difficulte',
            field=models.PositiveIntegerField(default=1, verbose_name='Сложность'),
        ),
    ]
