# Generated by Django 5.0.1 on 2024-02-26 20:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0005_remove_product_date_at_product_date_finish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount_pr',
            new_name='numbers',
        ),
        migrations.AddField(
            model_name='product',
            name='busy_numbers',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оставшихся мест'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_finish',
            field=models.DateField(default=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала тура'), verbose_name='Дата окончания тура'),
        ),
        migrations.AlterField(
            model_name='product',
            name='difficulte',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Сложность'),
        ),
    ]
