# Generated by Django 5.0.1 on 2024-02-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0006_rename_amount_pr_product_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='busy_numbers',
        ),
    ]
